# -*- coding: utf-8 -*-
"""bmi calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAwLvcCjWMyif3x-EUcMqqapxiyxDtTl
"""

weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = weight / (height ** 2)

if bmi < 18.5:
    category = "Underweight"
elif bmi < 25:
    category = "Normal weight"
elif bmi < 30:
    category = "Overweight"
else:
    category = "Obese"

print("Your BMI is", round(bmi, 2))
print("Category:", category)